import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

import { getServerSession } from "next-auth";
import SessionProvider from "./config/AuthProvider";
import NavBar from "./components/navBar/NavBar";
import User from "./schemas/user";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
const user: User = {
  name: "mock up",
  email: "mock up",
  password: "123",
  image:
    "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e8/The_Joker_at_Wax_Museum_Plus.jpg/330px-The_Joker_at_Wax_Museum_Plus.jpg",
};
export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const session = await getServerSession();

  return (
    <html lang="en">
      <body className={inter.className}>
        <SessionProvider session={session}>
          <NavBar />
          {children}
        </SessionProvider>
      </body>
    </html>
  );
}
